apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  ALLOWED_HOSTS: "backend-service,localhost,127.0.0.1"
  DJANGO_SETTINGS_MODULE: "SystemeRH.settings"
  DATABASE_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  SECRET_KEY: <base64-encoded-secret>
  DATABASE_NAME: <base64-encoded>
  DATABASE_USER: <base64-encoded>
  DATABASE_PASSWORD: <base64-encoded>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: registry.gitlab.com/your_project_name/your-app-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          env:
            - name: DATABASE_HOST
              value: "postgres-service"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP